### ISSUE TITLE
Morning session peer-to-peer code review 

### ISSUE THREAD

**Issue by enoqueJonas** [enoqueJonas/AweBooks#2]
Code review

**Comment by SimonGideon** [comment]
## :waffle:  Issue Based on PR  #1 

- [ ]  Clean codes in CSS file, I will suggest arranging them according to their appearance in the `index.html` it gets easy when you want to edit some elements working with a big project. Find it here :point_right: [Here](https://github.com/enoqueJonas/AweBooks/pull/1/commits/ea4a70d25a72d2b3ad1b181af8b717a878050344#diff-337cc548d34c6d80b758ad814ddd793a9ec155eb664e127c1fc4d8c5abd19b8aR1-R225)
- [ ] I like the consistency in your code from the arrangement of codes to your variable naming conventions :100: See it :point_right: [Here](https://github.com/enoqueJonas/AweBooks/pull/1/commits/c745ad8a3a2b734609570e14ed039990ad1b8f94#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R5-R12)

**Comment by AbeeraTahir** [comment]
Hi @enoqueJonas, 

Excellent work done by you. You have put a great effort into building that project. I believe your design will look more beautiful if you add the copyright section at the bottom of the main page. Good luck! :raised_hands:
